name: Deploy Streamlit to Google Cloud Run

on:
  push:
    branches:
      - main  # change if you're using a different default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and Push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/streamlit-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy streamlit-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/streamlit-app \
            --platform managed \
            --region asia-south1 \
            --allow-unauthenticated
